name: Create conda environment with docker python3.8env

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      ENVIRONMENT_NAME: python3.8env
      TEST_FILE: test.sh
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - name: Build environment
        uses: jbellister-slac/lcls-rhel6-conda-pack@e0c38e0d501ca34c5e33500e779ff28d13dd0d00
