name: Create RHEL7 compatible conda environment with docker

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      ENVIRONMENT_NAME: python3_rhel7_env
      ENVIRONMENT_FILE_PATH: python3_rhel7_env.yml
      TEST_FILE: test.sh
    runs-on: ubuntu-22.04
    name: Build environment
    steps:
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          df -h
      - name: Build environment
        uses: slaclab/lcls-rhel7-conda-pack@v1.1
